export const challenges = [
    "Say something kind to yourself 😊",
    "Tidy one little thing around you 🧹",
    "Take 3 deep breaths 🌬️",
    "Smile for 3 seconds 🙂",
    "Stretch your shoulders a bit 🙆‍♀️",
    "Send a nice message to someone 💬",
    "Drink a sip of water 💧",
    "Roll your shoulders gently 🙆‍♂️",
    "Relax your jaw for a moment 😌",
    "Sit up straight for 5 seconds 🪑",
    "Close your eyes for 2 seconds 😴",
    "Take one slow deep breath 🌬️",
    "Stretch your neck softly ↕️",
    "Think of one thing you're grateful for 🌼",
    "Tell yourself ‘I’m doing my best’ 💛",
    "Smile to yourself for a moment 😊",
    "Give yourself a tiny compliment ✨",
    "Think of a small win from today 🏆",
    "Throw one tiny thing you don't need 🗑️",
    "Organize one item near you 🧺",
    "Wipe one small surface 🧽",
    "Drink a little water 💧",
    "Stand up for 5 seconds 🧍",
    "Blink slowly 3 times to relax your eyes 👁️",
    "Send someone a positive emoji 💛",
    "Think of someone you appreciate 🫶",
    "Say one kind sentence to yourself 🪞",
    "Do a tiny happy dance 💃",
    "Hum a tune for one second 🎶",
    "Imagine your favorite snack 🍪",
    "Picture a place you love 🌄",
    "Think of a funny moment 😂",
    "Touch something warm or cozy ☕",
    "Look around and spot 3 colors 🌈",
    "Count backwards from 5 slowly 🔢",
    "Tap your fingers gently on the table ✋",
  ];
  